[package]
name = "loom"
version = "0.1.0"
authors = ["Jacob Ochoa <jacob.ochoa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
uuid = "0.8"
serde_json = "1"
rocket_contrib = "0.4"